### ISSUE TITLE
Criar DDL

### ISSUE THREAD

**Issue by ArturTomasi** [Manager2020A/CleanupSystem#2]
Scripts devem ser MySQL

**Comment by chriskroth** [comment]
@ArturTomasi 
Opa, segue os scripts do banco de dados. Só precisa alterar o 'mydb' pelo nome correto do banco de dados.

[banco_quarta.zip](https://github.com/Manager2020A/CleanupSystem/files/4332736/banco_quarta.zip)

Se possível, confirma que viu essa mensagem ;)
Vlwww!!!

**Comment by ArturTomasi** [comment]
> @ArturTomasi
> Opa, segue os scripts do banco de dados. Só precisa alterar o 'mydb' pelo nome correto do banco de dados.
> 
> [banco_quarta.zip](https://github.com/Manager2020A/CleanupSystem/files/4332736/banco_quarta.zip)
> 
> Se possível, confirma que viu essa mensagem ;)
> Vlwww!!!

Show de bola  @chriskroth... mas vou ir fazendo aos poucos... elaborei um exemplo utilizado as migrations (flyway) e postgressql
